baseURL: "https://atharvashah.netlify.app/"
languageCode: en-us
title: Atharva Shah
paginate: 5
theme: ['hugo-shortcode-roneo-collection','PaperMod']

#This will stop tracking in July 2023. Just migrate to Analytics 4 and make changes in hugo. Google it. You'll be fine.
googleAnalytics: UA-216150796-2 
 
#COMMENTS
disqusShortname: https-atharvashah-netlify-app

#FOR SEO
enableRobotsTXT: false


buildDrafts: false
buildFuture: false
buildExpired: false
imaging:
  anchor: Smart
  bgColor: '#ffffff'
  hint: photo
  quality:    
  resampleFilter: Box

#SITE MENU
menu:
  main:
    - identifier: tech
      name: ğŸ’»Tech
      url: /posts/tech/
      weight: 1
    - identifier: personal
      name: ğŸ¿Personal
      url: /posts/personal/
      weight : 2
    - identifier: about
      name: ğŸ‘¨ğŸ»About
      url: /about/
      weight: 3
    - identifier: search
      name: ğŸ”Search
      url: /search/
      weight: 4
    - identifier: archive
      name: ğŸ“œArchive
      url: /archives/
      weight: 4
    - identifier: tags
      name: ğŸ·ï¸Tags
      url: /tags/
      weight: 4
    

#REQUIRED FOR SEARCH FUNCTIONALITY.
outputs:
    home:
        - HTML
        - RSS
        - JSON # is necessary

#CIRTICAL SECTION
params:
    defaultTheme: dark
    assets:
      favicon: "/favicon.ico"
      favicon16x16:  "/favicon-16x16.png"
      favicon32x32:  "/favicon-32x32.png"
      disableHLJS: true
    
    env: production
    
    label:
      text: "Atharva Shah"
      icon: "/profile/header_button.webp"
      iconHeight: 30
      iconWidth: 30
    
    title: Atharva Shah
    description: "ğŸ‘‹ Howdy! I am Atharva Shah and on this blog I ruminate about tech, programming, entertainment and the fine things in life."
    keywords: [Blog, AtharvaShah, Entertainment, Technology]
    
    cover:
      hidden: false # hide everywhere but not in structured data
      hiddenInList: true # hide on list pages and home
      hiddenInSingle: false # hide on single page
      responsiveImages: false # Reduce generation time and size of the site, you can disable this feature

    DateFormat: "January 2, 2006"
    ShowReadingTime: true
    ShowShareButtons: true
    ShowPostNavLinks: true
    ShowBreadCrumbs: true
    ShowCodeCopyButtons: true
    ShowWordCount: true
    ShowRssButtonInSectionTermList: true
    UseHugoToc: false
    disableSpecial1stPost: false
    disableScrollToTop: false
    hidemeta: false
    hideSummary: false
    showtoc: true
    tocopen: true
    comments: true
    
    # SEARCH
    fuseOpts:
        isCaseSensitive: true
        useExtendedSearch: false
        includeMatches: false
        minMatchCharLength: 3
        keys: ["title", "description"]
    
    homeInfoParams:
      Title: "\U0001F44B Howdy!"
      Content: Welcome, this is where I blog about programming, entertainment and life.
    
    socialIcons:
      - name: github
        url: "https://github.com/HighnessAtharva"
      - name : linkedin
        url : https://www.linkedin.com/in/atharva-shah-5873a2111/
      - name: email
        url: "mailto:highnessatharva@gmail.com"
      - name: twitter
        url: "https://twitter.com/cultist_dev"
      - name: letterboxd
        url: "https://letterboxd.com/HighnessAtharva"
      - name: lastfm
        url: "https://www.last.fm/user/HighnessAtharva"
      - name: rss
        url: "/index.xml"
      
    
    profileMode:
      
      enabled: true # needs to be explicitly set
      title: Atharva Shah
      subtitle: "ğŸ‘‹ Howdy! I ruminate about tech, programming, entertainment and the fine things in life."                              
      imageUrl: "/profile/profile_icon.gif"
      imageWidth: 250
      imageHeight: 250
      linkFullImages: false
      imageTitle: AS
      
      buttons:
        # - name: About Me ğŸ‘‹
        #   url: /about/
        # - name: Blog ğŸ“
        #   url: blog
        # - name : Archive âŒ›
        #   url: /archives/
        # - name : Tags ğŸ·ï¸
        #   url: /tags/
        - name: Projects ğŸ› ï¸
          url: /projects/
        - name: Portfolio âš¡
          url: https://highnessatharva.github.io 
        - name : Resume ğŸ“
          url: https://github.com/HighnessAtharva/Resume/blob/master/Atharva-Shah-Resume-2023.pdf 

