baseURL: "https://atharvashah.netlify.app/"
languageCode: en-us
title: Atharva Shah
paginate: 5
theme: PaperMod

#This will stop tracking in July 2023. Just migrate to Analytics 4 and make changes in hugo. Google it. You'll be fine.
googleAnalytics: UA-216150796-2 
 
#COMMENTS
disqusShortname: https-atharvashah-netlify-app

#FOR SEO
enableRobotsTXT: true


buildDrafts: false
buildFuture: false
buildExpired: false
imaging:
  anchor: Smart
  bgColor: '#ffffff'
  hint: photo
  quality:    
  resampleFilter: Box

#SITE MENU
menu:
  main:
    - identifier: blog
      name: Blog
      url: /blog/
      weight : 1
    - identifier: about
      name: About
      url: /about/
      weight: 2
    
    - identifier: search
      name: Search
      url: /search/
      weight: 3

#REQUIRED FOR SEARCH FUNCTIONALITY.
outputs:
    home:
        - HTML
        - RSS
        - JSON # is necessary

#CIRTICAL SECTION
params:
    defaultTheme: dark
    assets:
      favicon: "/favicon.ico"
      favicon16x16:  "/favicon-16x16.png"
      favicon32x32:  "/favicon-32x32.png"
      disableHLJS: true
    
    env: production
    
    label:
      text: "Atharva Shah"
      icon: "/profile/header_button.gif"
      iconHeight: 30
    
    title: Atharva Shah
    description: "Howdy üëã! I am Atharva Shah and on this blog I ruminate about tech, programming, entertainment and the fine things in life."
    keywords: [Blog, AtharvaShah, Entertainment, Technology]
    
    cover:
      hidden: false # hide everywhere but not in structured data
      hiddenInList: true # hide on list pages and home
      hiddenInSingle: false # hide on single page
      responsiveImages: false # Reduce generation time and size of the site, you can disable this feature

    DateFormat: "January 2, 2006"
    ShowReadingTime: true
    ShowShareButtons: true
    ShowPostNavLinks: true
    ShowBreadCrumbs: true
    ShowCodeCopyButtons: true
    ShowWordCount: true
    ShowRssButtonInSectionTermList: true
    UseHugoToc: false
    disableSpecial1stPost: false
    disableScrollToTop: false
    comments: true
    hidemeta: false
    hideSummary: false
    showtoc: false
    tocopen: false
    comments: true
    
    # SEARCH
    fuseOpts:
      isCaseSensitive: true
      useExtendedSearch: true
      location: 0
      distance: 0
      threshold: 0.0
      minMatchCharLength: 4
      keys: ["title","content", "tags", "author", "date", "description"]
    
    homeInfoParams:
      Title: "Howdy \U0001F44B"
      Content: Welcome, this is where I blog about programming, entertainment and life.
    
    socialIcons:
      - name: twitter
        url: "https://twitter.com/HighnessAlex"
      - name: github
        url: "https://github.com/HighnessAtharva"
      - name : linkedin
        url : https://www.linkedin.com/in/atharva-shah-5873a2111/
      - name: email
        url: "mailto:highnessatharva@gmail.com"
    
    profileMode:
      
      enabled: true # needs to be explicitly set
      title: Atharva Shah
      subtitle: "Howdy üëã! I ruminate about tech, programming, entertainment and the fine things in life "                              
      imageUrl: "/profile/profile_icon.gif"
      imageWidth: 250
      imageHeight: 250
      linkFullImages: false
      imageTitle: AS
      
      buttons:
        - name: About Me üëã
          url: /about/
        - name: Blog üìù
          url: blog
        - name : Archive ‚åõ
          url: /archives/
        - name : Tags üè∑Ô∏è
          url: /tags/
        - name : Resume üéì
          url: https://github.com/HighnessAtharva #Replace later

